### ISSUE TITLE
Auswahlliste Veranstaltung Wochenrhythmus  verwirrend

### ISSUE THREAD

**Issue by wayoda** [codeschluss/wupportal#10]
## Die Auswahlliste für  
* neue Veranstaltung
  * Stammdaten
    * Adresse 
      * Termine
        * Wochenrhythmus 
ist mit den Numerischen Werten zu verwirrend. (Negative Eingabe  möglich  ?)

Wie wäre es mit 
1. **Freitext**
1. wöchentlich
1. vierzehntägig
1. 3 Wochenrhythmus
1. 4 Wochenrhythmus
1. Monatlich 
1. Vierteljährlich

**Comment by SteffiSp** [comment]
ja zB wöchentlich > Wochentag-Auswahl > Uhrzeit von bis - Auswahl, so dass sowas rauskommt wie montags 15 - 17 Uhr wöchentlich 

oder eben monatlich > Wochentag-Auswahl > Auswahl 1.,2.,3.,4. Wochentag (mit mehrfach-Haken-Möglichkeit für zB 14-tägig im Monat) 

oder wahlweise Datumsauswahl/Kalender von bis + Uhrzeiten (hier so etwas wie "täglich jeweils von bis" ermöglichen sowie alternativ Freitext für zB wechselnde Uhrzeit (falls es ein Kurs ist zB der täglich ist, aber zu wechselnden Zeiten) - falls zu kompliziert, einfach normalen Freitext ermöglichen für die Terminbeschreibung

**Comment by Pseipel** [comment]
Ist aufgenommen und umgestezt worden. Sollte seit 4. März in der neuen Version online sein. Vielen Dank für die Anregungen.
