### ISSUE TITLE
Speichern Problem

### ISSUE THREAD

**Issue by Hanikhayat** [codeschluss/wupportal#11]
Hallo zusammen,

Es gibt ein kleines Problem wenn man die Aktivität ändern möchte, soll man immer „weiter“ tippen, sonst die Daten nicht geändert werden, auch wenn „Speichern“ gedrückt wird. 

LG
Hani Al Khayat

**Comment by Pseipel** [comment]
Danke für den Anmerkung. Das Problem sollte seit der neusten Version (seit ca einer Woche live) nicht mehr auftreten.
