### ISSUE TITLE
Termindarstellung verwirrend

### ISSUE THREAD

**Issue by SteffiSp** [codeschluss/wupportal#12]
Hi,

wenn ich mir den Termin der offenen Sprechstunde von Hand in Hand e.V. anschaue:

Stammdaten
Titel : Offene Sprechstunde
[etc. ...]
Kategorie : Ehrenamt
**Termine
2018-02-07 04:00:00 - 2018-12-19 07:00:00**

dann frag ich mich, ob sie wirklich am 7. Februar um 4 Uhr morgens eine Sprechstunde hatten und die dann erst im Dezember um 7 Uhr morgens wieder anbieten - und denke mir natürlich - wohl kaum. Es wird wohl eine regelmäßige sein, aber wann wohl nun wirklich?? Klappt da was mit der Termindarstellung nicht?

Es wäre auch schön, wenn der Organisationsname in der Termindarstellung verlinkt wäre, so dass man dort auch wieder zurück zu den Stammdaten der Organisation kommt, um zB anzurufen, wann die Termine der offenen Sprechstunde nun wirklich sind. So als Beispiel. :)

LG, Steffi

**Comment by Pseipel** [comment]
Hallo, wir haben den Terminkalender vor ca. einer Woche geupdated. Er bietet jetzt mehr Funktionen an und sollte wesentlich überischtlicher sein. Die Anregung zur Angabe, ob der Termin vor- oder nachmittags stattfindet, wird bis zur nächsten Version implementiert. Danke für den Hinweis.
