### ISSUE TITLE
Aktivitäten - Seite weiter-Funktion führt zu leerer Seite

### ISSUE THREAD

**Issue by SteffiSp** [codeschluss/wupportal#14]
Hi,

ich bekomme bei "Aktivitäten" 5 angezeigt, dort wird suggeriert, dass es aber 13 Angebote gibt. Also klicke ich ganz unten auf "Seite weiter", doch die dann angezeigte Seite ist leer. 

LG, Steffi

**Comment by vetemi** [comment]
siehe #5 Wurde behoben und wird bei der nächsten Auslieferung benutzbar.
