### ISSUE TITLE
[Client] Application Styles 

### ISSUE THREAD

**Issue by Pseipel** [codeschluss/wupportal#15]
Das Aussehen der App wird noch verändert werden.

**Comment by vetemi** [comment]
- Buttonfarben
- Navbarlink
- Footer am Ende

**Comment by schlusslicht** [comment]
This seems to be a dupe of https://github.com/codeschluss/wupportal/issues/66. Can it be closed, as https://github.com/codeschluss/wupportal/commit/b9f26cbda8415acf97ed15879be4f685e66c3959 was merged?

**Comment by schlusslicht** [comment]
Done.
