### ISSUE TITLE
Stammdaten Zusammenfassung: Statt Adresse wird der auszuführende Code angezeigt?

### ISSUE THREAD

**Issue by wayoda** [codeschluss/wupportal#3]
Bei Eingabe der Adressdaten wie in issue #2 beschrieben, erscheint auf der Seite Zusammenfassung statt der Adresse *Gathe 6, 42107 Wuppertal Elberfeld*

`Adresse : function () { if (this instanceof Promise) { return PROMISE_OBJECT_TO_STRING; } return originalObjectToString.apply(this, arguments); }`

Nach dem Speichern ist aber die richtige Adresse in den Stammdaten hinterlegt. Unter **Organisationen** bekommt man also die richtigen Daten angezeigt.

**Comment by vetemi** [comment]
Problem behoben. Bis morgen ausgeliefert.
