### ISSUE TITLE
[Schedules] Einstellung als werktags (Mo - Fr)

### ISSUE THREAD

**Issue by vetemi** [codeschluss/wupportal#39]
Viele Aktivitäten finden unter der Woche täglich statt (z.B. Migrationsberatung – Montags bis Freitags zu festen Zeiten).

Wenn man diese Aktivitäten als „täglich“ anlegt, werden sie auch für Samstag und Sonntag eingetragen und wenn sie über einen längeren Zeitraum laufen, ist es umständlich, die Wochenenden rauszunehmen.

**Comment by Pseipel** [comment]
Es gibt jetzt eine weitere Möglichkeit "werktags" auszuwählen.
