### ISSUE TITLE
Anzeige der Organisationen

### ISSUE THREAD

**Issue by sonjanoderer** [codeschluss/wupportal#5]
Hallo, In der Liste der Organisationen werden immer nur die ersten fünf angezeigt und wenn man auf "weiter" klickt, erscheint nichts. Erst wenn man "Einträge pro Seite" auf 100 stellt, werden alle angezeigt. Die Einträge sind nur teilweise alphabetisch geordnet. 
Viele Grüße, Sonja

**Comment by wayoda** [comment]
Gleiches Problem hier. Ich würde vorschlagen als Standardeinstellung die Liste der Organisationen automatisch nach Namen sortiert anzuzeigen.

@sonjanoderer um die Liste der Organisationen sortiert anzuzeigen kann man oben auf die Spaltenüberschrift klicken

**Comment by SteffiSp** [comment]
dasselbe bei Aktivitäten (siehe neus Issue), die "Einträge pro Seite"-Anzeigefunktion am besten automatisch auf 20 einstellen und auffälliger plazieren (immer vom Nichtwissen der Seiten-Benutzer ausgehen) und dann aber auch die "weiter"-Funktion ermöglichen.  LG, Steffi

**Comment by vetemi** [comment]
Entschuldigt die späte Rückmeldung. Wir waren sehr eingespannt in den letzten Wochen. 

Die Fehler in den Tabellen sind aber jetzt behoben. Wir haben zudem eure Anmerkungen aufgegriffen und haben jetzt bei den meisten Tabellen sinnvolle Vorsortierungen festgelegt. Außerdem sind standardmäßig jetzt 25 Einträge zu sehen.
