### ISSUE TITLE
Namen der Organisationen

### ISSUE THREAD

**Issue by sonjanoderer** [codeschluss/wupportal#6]
Hallo, 

alle Umlaute (ä, ö, ü) in den Namen der Organisationen werden nicht korrekt angezeigt. Wenn ich als Admin versuche, die Umlaute einzugeben und dann auf "speichern" drücke, erscheinen sie trotzdem nicht.
Viele Grüße,

Sonja

**Comment by SteffiSp** [comment]
ich füge mal noch dazu, dass es auch gut wäre, dem Sucher beim Namen der Organisation anzuzeigen, dass er den Orga-Namen auch anklicken kann (und so zu den Stammdaten selbiger gelangt), darauf kommt man nicht so schnell. Denn wenn man mit der Maus über den Namen geht, sollte das klassische "verlinkt"-Händchen auftauchen, tut es aber nicht. Also dem Sucher (der meist gewohnheits-verwöhnt ist) beom Orga-Namen deutlicher klarmachen, Hallo, ich bin auch ein Link zum Anklicken :)

**Comment by Pseipel** [comment]
Danke für das Feedback. Zu Punkt 1: Es sollte jetzt möglich sein, die Namen der Organisationen zu ändern. Vermutlich hatte die Eingabe einer Adresse gefehlt. Es wird ab jetzt nicht mehr möglich sein eine ohne Adresse abzuspeichern. Punkt 2: Gute Idee. Mit der nächsten Version wird der Zeiger anzeigen, dass bestimmte Tabellenteile anclickbar sind.
