### ISSUE TITLE
[Client] Landing page width > 100vw

### ISSUE THREAD

**Issue by bkis** [codeschluss/wupportal#62]
Win7_64, Firefox v63.0.3_64, 1920x1080

Landing page content overflows screen width, which causes a horizontal scroll bar (...und der is für'n Sack!). This is caused by ``margin-left: -15px; margin-right: -15px;`` applied to ``.row[_ngcontent-c23]`` around the page headline.  

![image](https://user-images.githubusercontent.com/9215743/48864377-ac9ece00-edcc-11e8-91f8-a7735d44301f.png)

**Comment by schlusslicht** [comment]
Since the whole project is being refactored, this issue will be resolved when migrating to the new client/frontend.

**Comment by schlusslicht** [comment]
Done (refactored).
