### ISSUE TITLE
[Client/Map] No mouse cursor change when hovering map markers

### ISSUE THREAD

**Issue by bkis** [codeschluss/wupportal#63]
Win7_64, Firefox v63.0.3_64
Ubuntu 18.04, Firefox v999.9999

People expect their mouse cursor to turn into a pointer &#128405; when hovering over something clickable. This doesn't happen for the map markers, which is quite misleading.

**Comment by schlusslicht** [comment]
Confirmed. This is still an issue.

**Comment by schlusslicht** [comment]
Closed with b5e48abef0c22c00fcf9b8a8ebb4d87ba93cde7d.
