### ISSUE TITLE
neue Organisation hinzufügen

### ISSUE THREAD

**Issue by sonjanoderer** [codeschluss/wupportal#7]
Hallo,

habe vergeblich versucht eine neue Organisation hinzuzufügen, über "Organisationen" und dann "neuer Eintrag". Nach Eingabe des Namens komme ich zu "Adresse" aber es erscheint nur ein weißes Feld und darunter "Abbrechen". Ich kann also nicht speichern.

Viele Grüße,

Sonja

**Comment by sonjanoderer** [comment]
Hallo ihr drei,

leider besteht das Problem weiter fort. Wenn ich nach Eingabe der Stammdaten auf "weiter" klicke oder direkt auf "Adresse" kommt nur ein weißer Bildschirm und ich werde gar nicht aufgefordert, die Adresse einzugeben.

Lg,

Sonja

**Comment by Pseipel** [comment]
Hi, das Problem sollte seit dem 4. März nicht mehr bestehen. Jetzt muss eine Adresse eingegeben werden, damit weiter geklickt werden kann.
