### ISSUE TITLE
[API] Dynamic Embeddings via Request

### ISSUE THREAD

**Issue by schlusslicht** [codeschluss/wupportal#74]
Implement (server- & client-side) request building/parsing to automagically embed all needed resources within the API server response.

**Comment by vetemi** [comment]
I'm going to start the server side implementation. As discussed, the API will exept the following form (in the first attempt):
`GET localhost/activities?filter=something&{OTHER_PARAMS}&embeddings=[addresses.suburb, tags, schedules]`

The array elements represent the field names of the model. The result will contain all specified sub resources within the _embedded attribute

**Comment by vetemi** [comment]
Server part is done and already merged into dev

**Comment by schlusslicht** [comment]
Client part done with a94fc52d9a27e91d73d9850c0b38239bd843c688.
